#ifndef _DISAMBIGUATOR_RULE_COLLECT_HPP_
#define _DISAMBIGUATOR_RULE_COLLECT_HPP_

#include <stemmer/disambiguator/rule-1a.hpp>
#include <stemmer/disambiguator/rule-1b.hpp>
#include <stemmer/disambiguator/rule-2.hpp>
#include <stemmer/disambiguator/rule-3.hpp>
#include <stemmer/disambiguator/rule-4.hpp>
#include <stemmer/disambiguator/rule-5.hpp>
#include <stemmer/disambiguator/rule-6a.hpp>
#include <stemmer/disambiguator/rule-6b.hpp>
#include <stemmer/disambiguator/rule-7.hpp>
#include <stemmer/disambiguator/rule-8.hpp>
#include <stemmer/disambiguator/rule-9.hpp>
#include <stemmer/disambiguator/rule-10.hpp>
#include <stemmer/disambiguator/rule-11.hpp>
#include <stemmer/disambiguator/rule-12.hpp>
#include <stemmer/disambiguator/rule-13a.hpp>
#include <stemmer/disambiguator/rule-13b.hpp>
#include <stemmer/disambiguator/rule-14.hpp>
#include <stemmer/disambiguator/rule-15a.hpp>
#include <stemmer/disambiguator/rule-15b.hpp>
#include <stemmer/disambiguator/rule-16.hpp>
#include <stemmer/disambiguator/rule-17a.hpp>
#include <stemmer/disambiguator/rule-17b.hpp>
#include <stemmer/disambiguator/rule-17c.hpp>
#include <stemmer/disambiguator/rule-17d.hpp>
#include <stemmer/disambiguator/rule-18a.hpp>
#include <stemmer/disambiguator/rule-18b.hpp>
#include <stemmer/disambiguator/rule-19.hpp>
#include <stemmer/disambiguator/rule-20.hpp>
#include <stemmer/disambiguator/rule-21a.hpp>
#include <stemmer/disambiguator/rule-21b.hpp>
#include <stemmer/disambiguator/rule-23.hpp>
#include <stemmer/disambiguator/rule-24.hpp>
#include <stemmer/disambiguator/rule-25.hpp>
#include <stemmer/disambiguator/rule-26a.hpp>
#include <stemmer/disambiguator/rule-26b.hpp>
#include <stemmer/disambiguator/rule-27.hpp>
#include <stemmer/disambiguator/rule-28a.hpp>
#include <stemmer/disambiguator/rule-28b.hpp>
#include <stemmer/disambiguator/rule-29.hpp>
#include <stemmer/disambiguator/rule-30a.hpp>
#include <stemmer/disambiguator/rule-30b.hpp>
#include <stemmer/disambiguator/rule-30c.hpp>
#include <stemmer/disambiguator/rule-31a.hpp>
#include <stemmer/disambiguator/rule-31b.hpp>
#include <stemmer/disambiguator/rule-32.hpp>
#include <stemmer/disambiguator/rule-34.hpp>
#include <stemmer/disambiguator/rule-35.hpp>
#include <stemmer/disambiguator/rule-36.hpp>
#include <stemmer/disambiguator/rule-37a.hpp>
#include <stemmer/disambiguator/rule-37b.hpp>
#include <stemmer/disambiguator/rule-38a.hpp>
#include <stemmer/disambiguator/rule-38b.hpp>
#include <stemmer/disambiguator/rule-39a.hpp>
#include <stemmer/disambiguator/rule-39b.hpp>
#include <stemmer/disambiguator/rule-40a.hpp>
#include <stemmer/disambiguator/rule-40b.hpp>
#include <stemmer/disambiguator/rule-41.hpp>
#include <stemmer/disambiguator/rule-42.hpp>

#endif /* _DISAMBIGUATOR_RULE_COLLECT_HPP_ */